@startuml
title "App Interaction"

left to right direction

actor "User" as user

rectangle FrontEnd {
    usecase "visualization:\n/map" as visualize
}

actor "App" as App

actor "cron" as cron

database "Postgres" as db

App <--> db : "getLatestSentiment()"

App --> visualize

@enduml