@startuml

left to right direction

actor "User" as user

rectangle FrontEnd {
    usecase "visualization:\n/map" as visualize
}

actor "App" as App

database "Postgres" as db

actor "cron" as cron

user <-- visualize

visualize <-- App :  "SentimentMap"

App <-- db : "getLatestSentiment()"

cron --> db : "storeLatestSentiment()"

db --> cron : "isTodayInDB()"

@enduml