@startuml


class DB_interaction
DB_interaction : connection : psycop2.connect
DB_interaction : cursor : NoneType
DB_interaction : getCityIndexesDict() : dict
DB_interaction : getCityLocations()
DB_interaction : getLatestSentiment() : pd.DataFrame
DB_interaction : isTodayInDB()
DB_interaction : storeLatestSentiment(sentimentDict)


class MarketSentiment
MarketSentiment : newsapi_key : os.environ
MarketSentiment : sentiment_classifier : transformers.pipeline
MarketSentiment : addCityIndexes(CityIndexesDict)
MarketSentiment : getSentiment() : dict


class SentimentMap
SentimentMap : fig : NoneType, Figure
SentimentMap : map_sentiment : dict
SentimentMap : sentimentDf : pd.DataFrame


@enduml